version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - wsl
    - ireturn
    - funcorder
    - tagalign
    - exhaustruct_v5
    - gomodguard
  settings:
      wrapcheck:
        ignore-sigs:
          - fmt.Errorf
          - errors.New
      varnamelen:
        ignore-names:
          - c
          - db
          - rw
          - r
          - w
          - id
      tagliatelle:
        case:
          rules:
            json: camel
            yaml: camel
            env: upperSnake
      revive:
        rules:
          - name: exported
            severity: warning
            disabled: true
